info:
  name: config setup
  type: http
  seq: 1

http:
  method: POST
  url: "{{BASE_URL}}/config"
  body:
    type: json
    data: |-
      {
        "name": "Ikemen",
        "description": "THIS IS A TEST",
        "allow_overwrite": true,
        "state_size": 4,
        "action_size": 2,
        "gamma": 0.99
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
