name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  fmt_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
      - name: Install fmt
        run: rustup component add rustfmt
      - name: check formatting
        run: cargo fmt --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Add targets
        run: |
          rustup target add x86_64-pc-windows-gnu
      - name: Build releases
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          cargo build --release
